apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    # Reef (v18) – stable, supported
    image: quay.io/ceph/ceph:v18.2.4
  dataDirHostPath: /var/lib/rook

  mon:
    count: 1
    allowMultiplePerNode: true

  mgr:
    count: 1

  dashboard:
    enabled: true
    ssl: false

  network:
    provider: host

  storage:
    useAllNodes: true
    useAllDevices: false
    devices:
      - name: "/dev/disk/by-id/nvme-CT1000T500SSD8_240646E9D957"
    config:
      osdsPerDevice: "1"

  crashCollector:
    disable: false

