apiVersion: v1
kind: Pod
metadata:
  name: ceph-test-pod
spec:
  containers:
  - name: tester
    image: busybox:1.36
    command: ["/bin/sh", "-c", "echo 'Hello from Ceph RBD' > /mnt/test/hello.txt && sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /mnt/test
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: ceph-test-pvc

