apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  restartPolicy: Never
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:12.3.2-base-ubuntu22.04
      command: ["bash", "-lc", "nvidia-smi && python - <<'PY'\nprint('CUDA container OK')\nPY"]
      resources:
        limits:
          nvidia.com/gpu: 1
