apiVersion: v1
kind: Pod
metadata:
  name: gpu-test3
spec:
  restartPolicy: Never
  containers:
    - name: nvidia-smi
      image: docker.io/nvidia/cuda:12.3.2-runtime-ubuntu22.04
      command: ["bash", "-lc", "nvidia-smi && sleep 3600"]
      resources:
        limits:
          nvidia.com/gpu: 1
