apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llama-server
  template:
    metadata:
      labels:
        app: llama-server
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: llama-server
      containers:
      - name: llama
        image: ghcr.io/ggerganov/llama.cpp:server-cuda
        args:
          - -m
          - /models/mistral-7b-instruct.Q4_K_M.gguf
          - --n-gpu-layers
          - "999"
          - -c
          - "2048"
          - --host
          - 0.0.0.0
          - --port
          - "8080"
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            nvidia.com/gpu.shared: 1
          limits:
            cpu: "4"
            memory: "8Gi"
            nvidia.com/gpu.shared: 1
        volumeMounts:
        - name: models
          mountPath: /models
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: llama-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: llama-service
  namespace: default
spec:
  selector:
    app: llama-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

